### ISSUE TITLE
Have fixed levels of intensity across waves.

### ISSUE THREAD

**Issue by zookae** [efruchter/Trait#11]
For the purposes of testing and data collection the variable levels of intensity can introduce so much variation that it becomes difficult to parse out changes in behavior vs changes in the wave structure. This may simply be fixing some parameter settings.

**Comment by efruchter** [comment]
To fix this, you can just not set the gene in your vector (leave it at its
default).

My other solution is to just hard-code it to 0.5 and not have it be a gene.

I'd prefer the first solution, since it keeps everything about the game as
a gene, which I like.

On Sun, Mar 10, 2013 at 9:44 AM, bukki notifications@github.com wrote:

> For the purposes of testing and data collection the variable levels of
> intensity can introduce so much variation that it becomes difficult to
> parse out changes in behavior vs changes in the wave structure. This may
> simply be fixing some parameter settings.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/efruchter/Trait/issues/11
> .

## 

Eric Fruchter
Georgia Institute of Technology
